using System;
using System.Collections.Generic;

namespace VodDownloader.Entities;

public static class Constant {
    public static Dictionary<String, String> SiteTypeDictionary { get; } = new(){
        // ffzy
        {"ffzy.tv","ffzy"},
        {"www.ffzy.tv","ffzy"},
        {"ffzy1.tv","ffzy"},
        {"www.ffzy1.tv","ffzy"},
        {"ffzy2.tv","ffzy"},
        {"www.ffzy2.tv","ffzy"},
        {"ffzy3.tv","ffzy"},
        {"www.ffzy3.tv","ffzy"},
        {"ffzy4.tv","ffzy"},
        {"www.ffzy4.tv","ffzy"},
        {"ffzy5.tv","ffzy"},
        {"www.ffzy5.tv","ffzy"},
        {"api.ffzyapi.com","ffzy"},
        {"cj.ffzyapi.com","ffzy"},
        // lzzy
        {"lzzy.tv","lzzy"},
        {"www.lzzy.tv","lzzy"},
        {"lzizy1.com","lzzy"},
        {"www.lzizy1.com","lzzy"},
        {"lzizy2.com","lzzy"},
        {"www.lzizy2.com","lzzy"},
        {"lzizy3.com","lzzy"},
        {"www.lzizy3.com","lzzy"},
        {"lzizy4.com","lzzy"},
        {"www.lzizy4.com","lzzy"},
        {"lzizy5.com","lzzy"},
        {"www.lzizy5.com","lzzy"},
        {"lzizy6.com","lzzy"},
        {"www.lzizy6.com","lzzy"},
        {"lzizy7.com","lzzy"},
        {"www.lzizy7.com","lzzy"},
        {"lzizy8.com","lzzy"},
        {"www.lzizy8.com","lzzy"},
        // ikunzy
        {"ikunzy.com","ikunzy"},
        {"www.ikunzy.com","ikunzy"},
        {"ikunzy.net","ikunzy"},
        {"www.ikunzy.net","ikunzy"},
        {"ikunzy.org","ikunzy"},
        {"www.ikunzy.org","ikunzy"},
        {"ikunzy.vip","ikunzy"},
        {"www.ikunzy.vip","ikunzy"},
        {"ikunzyapi.com","ikunzy"},
        {"www.ikunzyapi.com","ikunzy"},
        // yhzy
        {"yhzy.cc","yhzy"},
        {"www.yhzy.cc","yhzy"},
        // bfzy
        {"bfzy.tv","bfzy"},
        {"www.bfzy.tv","bfzy"},
        {"bfzy1.tv","bfzy"},
        {"www.bfzy1.tv","bfzy"},
        {"bfzy2.tv","bfzy"},
        {"www.bfzy2.tv","bfzy"},
        {"bfzy3.tv","bfzy"},
        {"www.bfzy3.tv","bfzy"},
        {"bfzy4.tv","bfzy"},
        {"www.bfzy4.tv","bfzy"},
        {"bfzy5.tv","bfzy"},
        {"www.bfzy5.tv","bfzy"},
        {"bfzy6.tv","bfzy"},
        {"www.bfzy6.tv","bfzy"},
        {"bfzy7.tv","bfzy"},
        {"www.bfzy7.tv","bfzy"},
        {"bfzy8.tv","bfzy"},
        {"www.bfzy8.tv","bfzy"},
        {"bfzy9.tv","bfzy"},
        {"www.bfzy9.tv","bfzy"},
        {"bfzy10.tv","bfzy"},
        {"www.bfzy10.tv","bfzy"},
    };
}
